---
- name: Setup provider
  ansible.builtin.set_fact:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server_port: "{{ f5_admin_port }}"
      validate_certs: false
  no_log: true    
  delegate_to: "{{ jump_host }}"

- setup:
    gather_subset:
      - min 
  delegate_to: "{{ jump_host }}"    
  
- name: Find Active Machine
  bigip_command:
    provider: "{{ provider }}"
    match: "any"
    warn: no
    commands:
      - bash -c "cat /var/prompt/ps1"
  register: result      
  delegate_to: "{{ jump_host }}"
  
- debug:
    var: result.stdout        

